In [1]:
import pandas as pd

In [5]:
df =pd.read_csv("placement.csv")

In [7]:
df.values    #in array format without column name

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

In [9]:
df_values = df.values

In [11]:
df_new = pd.DataFrame(df_values , columns = ['new_cgpa' , 'updated_resume','placed'])

In [13]:
df_new

    new_cgpa  updated_resume  placed
0       8.14            6.52     1.0
1       6.17            5.17     0.0
2       8.27            8.86     1.0
3       6.88            7.27     1.0
4       7.52            7.30     1.0
..       ...             ...     ...
95      6.33            6.38     0.0
96      8.23            7.76     1.0
97      6.65            7.78     0.0
98      8.14            5.63     1.0
99      6.09            6.61     0.0

[100 rows x 3 columns]

In [15]:
#second method

In [17]:
df.values

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

In [19]:
df_new2 = pd.DataFrame(df.values , columns = df.columns)

In [21]:
df_new2

    cgpa  resume_score  placed
0   8.14          6.52     1.0
1   6.17          5.17     0.0
2   8.27          8.86     1.0
3   6.88          7.27     1.0
4   7.52          7.30     1.0
..   ...           ...     ...
95  6.33          6.38     0.0
96  8.23          7.76     1.0
97  6.65          7.78     0.0
98  8.14          5.63     1.0
99  6.09          6.61     0.0

[100 rows x 3 columns]

# pipeline

In [24]:
#differnece betwwn column transformer and pipeline?
#both are containerisng 
#but in column transformer ek step ka output dusre ka input nahi bnata h ,
#but in pipeline ek step ka output dusre ka input bnta hai.

In [26]:
#Data --> separate (categorical ,numerical) ---->
#categorical data --->SimpleImputer fill ----->Encode
#numerical data --->SimpleImputer fill------>Standardize

#Apply === Alogirthm (LogisticRegression)

In [28]:
import numpy as np
import pandas as pd

In [32]:
df =pd.read_csv("covid_toy.csv")

In [34]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler ,OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [38]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=23)

In [40]:
#Define the columns that need to be processed
categorical_features = ['gender','city']
numeric_features = ['age','fever']

In [46]:
#create transformers
numeric_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy = 'mean')),
    ('scaler',StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy = 'most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown = 'ignore'))
])

#combine transformers
preprocessor = ColumnTransformer(
    transformers = [
        ('num',numeric_transformer,numeric_features),
        ('cat',categorical_transformer,categorical_features),
    ])