In [17]:
import numpy as np
import pandas as pd

In [18]:
df = pd.read_csv("supply_chain.csv")

In [19]:
df.head(2)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579

In [20]:
df.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
lb = LabelEncoder()

In [23]:
df['Product type']= lb.fit_transform(df['Product type'])
df['SKU']= lb.fit_transform(df['SKU'])
df['Customer demographics']= lb.fit_transform(df['Customer demographics'])
df['Location']= lb.fit_transform(df['Location'])
df['Inspection results']= lb.fit_transform(df['Inspection results'])
df['Transportation modes']= lb.fit_transform(df['Transportation modes'])
df['Routes']= lb.fit_transform(df['Routes'])

In [24]:
df.head(2)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,1,0,69.808006,55,802,8661.996792,2,58,7,96,...,4,29,215,29,46.279879,2,0.226410,2,1,187.752075
1,2,1,14.843523,95,736,7460.900065,0,53,30,37,...,4,23,517,30,33.616769,2,4.854068,2,1,503.065579

In [25]:
#ordinal encoding

In [26]:
df=pd.read_csv("supply_chain.csv")

In [39]:
df.head(2)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579

In [43]:
df = df.drop(columns = ['Price' , 'Availability' , 'Number of products sold' ,
                        'Revenue generated', 'Stock levels', 'Lead times',
                        'Order quantities','Lead time','Production volumes'	, 'Manufacturing lead time',
                        'Manufacturing costs' ,'Defect rates','Costs'])

In [46]:
df.head(2)

,Product type,SKU,Customer demographics,Shipping times,Shipping carriers,Shipping costs,Supplier name,Location,Inspection results,Transportation modes,Routes
0,haircare,SKU0,Non-binary,4,Carrier B,2.956572,Supplier 3,Mumbai,Pending,Road,Route B
1,skincare,SKU1,Female,2,Carrier A,9.716575,Supplier 3,Mumbai,Pending,Road,Route B

In [48]:
df = df.drop(columns = ['Shipping times','Shipping costs'])

In [50]:
df.head(2)

,Product type,SKU,Customer demographics,Shipping carriers,Supplier name,Location,Inspection results,Transportation modes,Routes
0,haircare,SKU0,Non-binary,Carrier B,Supplier 3,Mumbai,Pending,Road,Route B
1,skincare,SKU1,Female,Carrier A,Supplier 3,Mumbai,Pending,Road,Route B

In [54]:
from sklearn.preprocessing import OrdinalEncoder

In [56]:
df['Product type'].value_counts()

Product type
skincare     40
haircare     34
cosmetics    26
Name: count, dtype: int64

In [58]:
df['SKU'].value_counts()

SKU
SKU0     1
SKU63    1
SKU73    1
SKU72    1
SKU71    1
        ..
SKU30    1
SKU29    1
SKU28    1
SKU27    1
SKU99    1
Name: count, Length: 100, dtype: int64

In [60]:
df['Customer demographics'].value_counts()

Customer demographics
Unknown       31
Female        25
Non-binary    23
Male          21
Name: count, dtype: int64

In [62]:
df['Shipping carriers'].value_counts()

Shipping carriers
Carrier B    43
Carrier C    29
Carrier A    28
Name: count, dtype: int64

In [64]:
df['Supplier name'].value_counts()

Supplier name
Supplier 1    27
Supplier 2    22
Supplier 5    18
Supplier 4    18
Supplier 3    15
Name: count, dtype: int64

In [66]:
df['Supplier name'].value_counts()

Supplier name
Supplier 1    27
Supplier 2    22
Supplier 5    18
Supplier 4    18
Supplier 3    15
Name: count, dtype: int64

In [68]:
df.columns

Index(['Product type', 'SKU', 'Customer demographics', 'Shipping carriers',
       'Supplier name', 'Location', 'Inspection results',
       'Transportation modes', 'Routes'],
      dtype='object')

In [70]:
#3.

In [74]:
df = pd.read_csv("supply_chain.csv")

In [76]:
df.head(3)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282

In [78]:
a= pd.get_dummies(df , columns =  ['Product type', 'SKU', 'Customer demographics', 'Shipping carriers',
       'Supplier name', 'Location', 'Inspection results',
       'Transportation modes', 'Routes'],drop_first = True)

In [80]:
a =a.dropna()

In [82]:
a.head(2)

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,...,Location_Delhi,Location_Kolkata,Location_Mumbai,Inspection results_Pass,Inspection results_Pending,Transportation modes_Rail,Transportation modes_Road,Transportation modes_Sea,Routes_Route B,Routes_Route C
0,69.808006,55,802,8661.996792,58,7,96,4,2.956572,29,...,False,False,True,False,True,False,True,False,True,False
1,14.843523,95,736,7460.900065,53,30,37,2,9.716575,23,...,False,False,True,False,True,False,True,False,True,False

In [84]:
a = a.astype(int)

In [86]:
a

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,...,Location_Delhi,Location_Kolkata,Location_Mumbai,Inspection results_Pass,Inspection results_Pending,Transportation modes_Rail,Transportation modes_Road,Transportation modes_Sea,Routes_Route B,Routes_Route C
0,69,55,802,8661,58,7,96,4,2,29,...,0,0,1,0,1,0,1,0,1,0
1,14,95,736,7460,53,30,37,2,9,23,...,0,0,1,0,1,0,1,0,1,0
2,11,34,8,9577,1,10,88,2,8,12,...,0,0,1,0,1,0,0,0,0,1
3,61,68,83,7766,23,13,59,6,1,24,...,0,1,0,0,0,1,0,0,0,0
4,4,26,871,2686,5,3,56,8,3,5,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,77,65,672,7386,15,14,26,9,8,18,...,0,0,1,0,1,0,0,0,0,0
96,24,29,324,7698,67,2,32,3,5,28,...,0,0,1,0,1,0,1,0,0,0
97,3,56,62,4370,46,19,4,9,7,10,...,0,0,1,0,0,0,1,0,0,0
98,19,43,913,8525,53,1,27,7,1,28,...,0,0,0,0,1,1,0,0,0,0
99,68,17,627,9185,55,8,59,6,1,29,...,0,0,0,0,0,1,0,0,1,0

In [88]:
df = a.copy()

In [90]:
x = df.drop(columns = ['Routes_Route C'])

In [92]:
y=df['Routes_Route C']

In [94]:
from sklearn.model_selection import train_test_split

In [96]:
x_train , x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [98]:
np.round(x_train.describe() , 1)

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,...,Location_Chennai,Location_Delhi,Location_Kolkata,Location_Mumbai,Inspection results_Pass,Inspection results_Pending,Transportation modes_Rail,Transportation modes_Road,Transportation modes_Sea,Routes_Route B
count,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0
mean,49.9,49.9,453.2,5821.6,47.5,15.9,47.5,5.8,5.2,17.2,...,0.2,0.2,0.2,0.3,0.2,0.4,0.3,0.3,0.2,0.4
std,32.4,31.5,302.0,2704.4,30.8,8.7,26.9,2.8,2.6,8.6,...,0.4,0.4,0.4,0.4,0.4,0.5,0.4,0.4,0.4,0.5
min,1.0,1.0,8.0,1061.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,18.5,21.2,161.0,2938.5,21.0,8.0,25.5,3.0,3.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,52.0,49.0,410.0,6093.5,46.5,16.5,51.5,6.0,5.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,79.0,78.8,701.8,8214.5,73.0,23.2,69.5,8.0,7.2,25.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
max,99.0,100.0,987.0,9866.0,100.0,30.0,94.0,10.0,9.0,30.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [109]:
from sklearn.preprocessing import StandardScaler

In [111]:
sc = StandardScaler()

In [117]:
x_train_sc = sc.fit_transform(x_train)

In [119]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [121]:
np.round(x_train_new.describe() , 1)

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,...,Location_Chennai,Location_Delhi,Location_Kolkata,Location_Mumbai,Inspection results_Pass,Inspection results_Pending,Transportation modes_Rail,Transportation modes_Road,Transportation modes_Sea,Routes_Route B
count,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0
mean,0.0,-0.0,0.0,0.0,-0.0,0.0,0.0,-0.0,-0.0,0.0,...,-0.0,0.0,-0.0,0.0,0.0,-0.0,-0.0,0.0,0.0,0.0
std,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
min,-1.5,-1.6,-1.5,-1.8,-1.6,-1.7,-1.7,-1.7,-1.6,-1.9,...,-0.5,-0.4,-0.5,-0.6,-0.5,-0.9,-0.6,-0.6,-0.5,-0.8
25%,-1.0,-0.9,-1.0,-1.1,-0.9,-0.9,-0.8,-1.0,-0.8,-0.8,...,-0.5,-0.4,-0.5,-0.6,-0.5,-0.9,-0.6,-0.6,-0.5,-0.8
50%,0.1,-0.0,-0.1,0.1,-0.0,0.1,0.2,0.1,-0.1,0.1,...,-0.5,-0.4,-0.5,-0.6,-0.5,-0.9,-0.6,-0.6,-0.5,-0.8
75%,0.9,0.9,0.8,0.9,0.8,0.9,0.8,0.8,0.8,0.9,...,-0.5,-0.4,-0.5,1.7,-0.5,1.1,1.6,1.7,-0.5,1.3
max,1.5,1.6,1.8,1.5,1.7,1.6,1.7,1.5,1.4,1.5,...,2.1,2.4,1.9,1.7,1.9,1.1,1.6,1.7,2.2,1.3

In [123]:
np.round(x_train.describe() , 1)

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,...,Location_Chennai,Location_Delhi,Location_Kolkata,Location_Mumbai,Inspection results_Pass,Inspection results_Pending,Transportation modes_Rail,Transportation modes_Road,Transportation modes_Sea,Routes_Route B
count,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0
mean,49.9,49.9,453.2,5821.6,47.5,15.9,47.5,5.8,5.2,17.2,...,0.2,0.2,0.2,0.3,0.2,0.4,0.3,0.3,0.2,0.4
std,32.4,31.5,302.0,2704.4,30.8,8.7,26.9,2.8,2.6,8.6,...,0.4,0.4,0.4,0.4,0.4,0.5,0.4,0.4,0.4,0.5
min,1.0,1.0,8.0,1061.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,18.5,21.2,161.0,2938.5,21.0,8.0,25.5,3.0,3.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,52.0,49.0,410.0,6093.5,46.5,16.5,51.5,6.0,5.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,79.0,78.8,701.8,8214.5,73.0,23.2,69.5,8.0,7.2,25.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
max,99.0,100.0,987.0,9866.0,100.0,30.0,94.0,10.0,9.0,30.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [125]:
from sklearn.preprocessing import MinMaxScaler

In [127]:
mn = MinMaxScaler()

In [129]:
x_train_mn = mn.fit_transform(x_train)

In [131]:
x_train_new = pd.DataFrame(x_train_mn , columns = x_train.columns)

In [133]:
np.round(x_train_new.describe() , 1)

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,...,Location_Chennai,Location_Delhi,Location_Kolkata,Location_Mumbai,Inspection results_Pass,Inspection results_Pending,Transportation modes_Rail,Transportation modes_Road,Transportation modes_Sea,Routes_Route B
count,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0
mean,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.6,...,0.2,0.2,0.2,0.3,0.2,0.4,0.3,0.3,0.2,0.4
std,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,...,0.4,0.4,0.4,0.4,0.4,0.5,0.4,0.4,0.4,0.5
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,0.2,0.2,0.2,0.2,0.2,0.2,0.3,0.2,0.2,0.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.5,0.5,0.4,0.6,0.5,0.5,0.5,0.6,0.5,0.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,0.8,0.8,0.7,0.8,0.7,0.8,0.7,0.8,0.8,0.8,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
max,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0