# Machine Learning (ML) MOdeling:

In [ ]:
'''
Machine learning (ML) modeling is the process of creating a program that can learn from data and make predictions 
or decisions without being explicitly programmed.
Here's a simple explanation of the key steps in ML modeling:

1. Define the Problem
Decide what you want your ML model to do. For example:
Predict house prices (regression).
Classify emails as spam or not spam (classification).
Group customers with similar behavior (clustering).

2. Collect Data
Gather the data the model will learn from. For example:
Sales data, images, text, or sensor readings.
Ensure the data is clean, accurate, and relevant.

3. Prepare the Data
Clean the data: Handle missing values or incorrect data.
Transform the data: Convert it into a format the model can understand (e.g., converting text to numbers).
Split the data:
Training set: Used to train the model.
Testing set: Used to check how well the model works on unseen data.

4. Choose a Model
Pick the type of ML model based on your problem. Common models include:
Linear Regression
Decision Trees
Neural Networks
Support Vector Machines (SVMs)

5. Train the Model
Feed the training data to the model so it can learn patterns and relationships in the data.

6. Evaluate the Model
Test the model on the testing set to see how well it performs. Common metrics include:
Accuracy
Precision
Recall
Mean Squared Error (for regression)

7. Tune the Model
Adjust parameters (hyperparameters) to improve the model’s performance, like:
Learning rate
Number of layers (in a neural network)
Maximum depth (in a decision tree)

8. Deploy the Model
Once the model works well, use it in real-world applications to make predictions.

9. Monitor and Update
Regularly check the model’s performance and retrain it if needed as new data becomes available.
'''

# why to do ML Modelling

In [ ]:
'''
We build machine learning models to solve real-world problems that are too complex for humans to program manually. 
ML allows computers to learn patterns from data and make decisions or predictions automatically.

Here's why we do it:

1. Automation
ML can automate repetitive tasks, saving time and reducing human effort. For example:
Automatically sorting spam emails.
Detecting defects in manufacturing processes.
2. Accuracy and Efficiency
ML can process large amounts of data quickly and make decisions with a high level of accuracy. For instance:
Diagnosing diseases from medical images more accurately than human doctors in some cases.
Predicting product demand based on past trends.
3. Handling Complex Patterns
Some problems involve patterns that are too subtle or complex for humans to detect. ML models can uncover these patterns. Examples include:
Detecting fraud in financial transactions.
Recommending products on e-commerce platforms.
4. Adaptability
Unlike traditional software, ML systems can adapt and improve as more data becomes available. For instance:
A weather prediction model becomes more accurate as it learns from new weather data.
Self-driving cars improve their navigation with more driving experience.
5. Personalization
ML enables tailored experiences for individuals, such as:
Personalized content recommendations on streaming platforms like Netflix.
Customized shopping experiences on websites like Amazon.
6. Decision Support
ML helps businesses and organizations make better decisions by providing insights from data. For example:
Predicting customer churn so companies can take action to retain clients.
Optimizing supply chains by predicting demand fluctuations.
7. Cost Reduction
By improving efficiency and accuracy, ML can save money in various industries. For example:
Reducing costs in healthcare by predicting diseases early.
Saving energy by optimizing power grids.
8. Driving Innovation
ML opens doors to new possibilities, such as:
Generating creative content like artwork or music.
Exploring space with autonomous robots.
'''

# Machine learning can be divided into four main types

In [ ]:
#depending on how the model learns and the kind of problem it solves:
'''
1. Supervised Learning
What it does: The model learns from labeled data. Each input has a corresponding correct output, and the goal is to
predict the output for new, unseen inputs.
Examples:
Predicting house prices based on features like size, location, and age (regression).
Classifying emails as spam or not spam (classification).
Algorithms:
Linear Regression
Decision Trees
Support Vector Machines (SVMs)
Neural Networks
                                                                                                                                      
2. Unsupervised Learning
What it does: The model works with unlabeled data and tries to find hidden patterns or structures in the data.
Examples:
Grouping customers with similar purchasing habits (clustering).
Identifying unusual network activity that could indicate a cyberattack (anomaly detection).
Algorithms:
K-Means Clustering
Principal Component Analysis (PCA)
Autoencoders
                  
3. Semi-Supervised Learning
What it does: Combines both labeled and unlabeled data. A small amount of labeled data helps the model learn, while the large amount of unlabeled data improves its performance.
Examples:
Identifying rare diseases where labeled medical data is scarce.
Classifying documents using a mix of labeled and unlabeled text.
Why it’s used: It’s helpful when labeling data is expensive or time-consuming.
                  
4. Reinforcement Learning
What it does: The model learns by interacting with an environment and receiving feedback in the form of rewards or penalties. The goal is to maximize the total reward over time.
Examples:
Teaching robots to walk or play soccer.
Training AI to play games like chess or Go.
Optimizing traffic light systems for smoother traffic flow.
Key Components:
Agent: The learner (e.g., a robot).
Environment: Where the agent interacts (e.g., a game).
Reward: Feedback for the agent’s actions.
'''

# 1.Supervised Learning

In [ ]:
'''
In supervised learning, we work with labeled data. The output (target) can be discrete or continuous.

For Discrete Data
Output: Predict a continuous numeric value.

Algorithms:
Logistic Regression
Decision Trees
Random Forest
Naive Bayes
Neural Networks (for classification tasks)


For Continuous Data
Task: Regression
Output: Predict a continuous numeric value.

Algorithms:
Linear Regression
Polynomial Regression
Random Forest Regression
Support Vector Regression (SVR)
Neural Networks (for regression tasks)
'''

In [7]:
# df ---> x,y
# x --->x_train , x_test
# y---->y_train , y_test

# model(x_train,y_train)
# model(x_test) ---> output???---->y_pred
# actual_output = y_test

# check difference = y_pred - y_test

In [9]:
import numpy as np

In [11]:
import pandas as pd

In [13]:
df = pd.read_csv("insurance.csv")

In [15]:
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [17]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder

In [23]:
lb=LabelEncoder()

In [29]:
df['sex']=lb.fit_transform(df['sex'])
df['region']=lb.fit_transform(df['region'])
df['smoker']=lb.fit_transform(df['smoker'])

In [31]:
df.head(2)

   age  sex    bmi  children  smoker  region     charges
0   19    0  27.90         0       1       3  16884.9240
1   18    1  33.77         1       0       2   1725.5523

In [33]:
x = df.drop(columns = ['charges'])

In [35]:
y=df['charges']

In [37]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [43]:
from sklearn.linear_model import LinearRegression

In [123]:
lr=LinearRegression()

In [125]:
lr.fit(x_train , y_train)

LinearRegression()

In [127]:
y_pred = lr.predict(x_test)

In [129]:
#It tells you how well the model's predictions align with the actual data.
from sklearn.metrics import r2_score

In [131]:
r2_score(y_test ,y_pred)

0.7833463107364538